# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3edhgJx8NsArOU9k4riuui-g6nGSpxW

# Assignment 1  
02-Feb-2026   | DAY 1
"""

#1.
name='''Hi How are you?
        Started learing python.
        It's really interesting.'''
name[:]

name[-10:-5]

name[3:12]

name[12:3]

name[5,6]  #its work on only integers like matrix but here are all strings

name[-4:-12]

name[::2]

name[::-2]

#2.
l1=['a','b',20,30,'t',100,300,400,'Happy','major']
l1[:]

l1[::3]

l1[::-2]

l1[-2]
l1[8]
l1[l1.index('Happy')]

type(l1[3])

l1[5:8]

#3.
l2=[1,2,3,5,['a','b','work hard'],100,200,"Success"]
l2

l2[4]

l2[1:5]

l2[7]

l2[7][2]

l2[7][2:]

l2[:3]

l2[3:]

#4.
L2=[1,2,3,5,['a','b','work hard'],100,200,"Success"]
L2

p=L2[4][1]='BEE'
print(L2)

#5.
del L2[4][1]
L2
#Or
L2[4].pop(1)
L2

#6.
L2.extend([{'insect':['bee','moth'],'bird':['parrot','sparrow']}])
L2

#7.
L2[8].get("insect")
#Or
L2[8]['insect']

#8.
d1={'a':10,'b':20,'c':30}
L2[1]=d1
L2
#OR
L2.insert(1,d1)

#9.
L2[1]['a']
#OR
L2[1].get('a')

#10.
l2 =[1,2,3,5, (90,40,50,10), 'Python', 400 ,['a', 'b', 'work hard'],100 , 200,"Success", (200,300, "Hundreds")]
l2

l2[4][2]

l2[5][:]

l2[2][:]  #int object is not subscriptable

l2[1:5]

l2[5]

l2[5][3:-1]

l2[-1]

l2[-4,-3]  #list indices must be integers or slices, not tuple

l2[-4:-10]

l2[7][2]

l2[-7][2:]

l2[:-3]

l2[-3:]

"""#### IF-elif-else:
11.	Ask user to enter the marks and define if the user got distinction, first class, second class, pass, Fails

If marks are more than 80 output must be “You got distinction”

For marks more than 60 output must be “You got First class”

Marks more than 40 will display “You got second class”

Marks more than or equal to 35 “PASS” Otherwise Fail

"""

#using if-else:
marks=input("Enter a marks:")
if (not marks.isalnum() and not marks.isalpha()) or marks.isdigit():
  marks=int(marks)
  if marks < 0 or marks > 100:
    print("Invalid marks")
  elif marks > 80 and marks <=100:
    print("You got distinction")
  elif marks > 60:
    print("You got First class")
  elif marks > 40 :
    print("You got second class")
  elif marks >=35:
    print("Pass")
  else:
    print("Fail")

else:
  print("Enter a valid marks pls.")

#using function:
marks=input("Enter your marks: ")
def student(marks):
  if (not marks.isalnum() and not marks.isalpha()) or marks.isdigit():
   marks=int(marks)
   if marks < 0 or marks > 100:
     print("Invalid marks")
   elif marks > 80 and marks <=100:
     print("You got distinction")
   elif marks > 60:
     print("You got First class")
   elif marks > 40 :
     print("You got second class")
   elif marks >=35:
    print("Pass")
   else:
     print("Fail")

  else:
    print("Enter a valid marks pls.")

student(marks)

#use of return function
mark=input("Enter a marks: ")
def calculate(mark):
  if (not mark.isalnum() and not mark.isalpha()) or mark.isdigit():
    mark=int(mark)
    if mark > 100 or mark < 0:
      result="pls Enter a valid marks. "
    elif mark > 80 and marks <=100:
      result="You got distinction"
    elif mark > 60:
      result="You got First class"
    elif mark > 40 :
      result="You got second class"
    elif mark >=35:
      result="Pass"
    else:
      result="Fail"
  else:
    result="Enter a logoical marks yaar..."

  return result

calculate(mark)

"""12.	Ask user to enter information about salary of the employee per year and rating received as A, B, C, D

If salary upto 5 lpa then increament based on ratings are  A = 16% , B=12%, C= 10%, D=6%

If salary upto 10 lpa then increament based on ratings are  A = 14% , B=10%, C= 8%, D=6%

If salary upto 15 lpa then increament based on ratings are  A = 8% , B=6%, C= 4%, D = no increment

If salary upto 23 lpa then increament based on ratings are  A = 7% , B=5%, C= 4%, D=no

"""

#simple
salary=float(input("Enter a salary per year:"))
if salary < 500000:
  rating=input("Enter increment ratings:(A/B/C/D)").upper()
  if rating=='A':
    print("Increment is 16%")
    salary=salary+salary*0.16
    print("After increment salary is: ",salary)
  elif rating=='B':
    print("Increment is 12%")
    salary=salary+salary*0.12
    print("After increment salary is: ",salary)
  elif rating=='C':
    print("Increment is 10%")
    salary=salary+salary*0.10
    print("After increment salary is: ",salary)
  else:
    print("Increment is 6%")
    salary =salary+salary *0.06
    print("After increment salary is: ",salary)

elif salary < 1000000:
  rating=input("Enter increment ratings:(A/B/C/D)").upper()
  if rating=='A':
    print("Increment is 14%")
    salary=salary+salary*0.14
    print("After increment salary is: ",salary)
  elif rating=='B':
    print("Increment is 10%")
    salary=salary+salary*0.10
    print("After increment salary is: ",salary)
  elif rating=='C':
    print("Increment is 8%")
    salary=salary+salary*0.8
    print("After increment salary is: ",salary)
  else:
    print("Increment is 6%")
    salary =salary+salary *0.06
    print("After increment salary is: ",salary)

elif salary < 1500000:
  rating=input("Enter increment ratings:(A/B/C/D)").upper()
  if rating=='A':
    print("Increment is 8%")
    salary=salary+salary*0.8
    print("After increment salary is: ",salary)
  elif rating=='B':
    print("Increment is 6%")
    salary=salary+salary*0.6
    print("After increment salary is: ",salary)
  elif rating=='C':
    print("Increment is 4%")
    salary=salary+salary*0.4
    print("After increment salary is: ",salary)
  else:
    print(" NO Increment ")

elif salary < 2300000:
  rating=input("Enter increment ratings:(A/B/C/D)").upper()
  if rating=='A':
    print("Increment is 7%")
    salary=salary+salary*0.7
    print("After increment salary is: ",salary)
  elif rating=='B':
    print("Increment is 5%")
    salary=salary+salary*0.5
    print("After increment salary is: ",salary)
  elif rating=='C':
    print("Increment is 4%")
    salary=salary+salary*0.4
    print("After increment salary is: ",salary)
  else:
    print(" NO Increment ")

# using function:
salary=float(input("Enter a salary per year:"))
def info(salary):
  if salary < 500000:
    rating=input("Enter increment ratings:(A/B/C/D)").upper()
    if rating=='A':
     print("Increment is 16%")
     salary=salary+salary*0.16
     print("After increment salary is: ",salary)
    elif rating=='B':
      print("Increment is 12%")
      salary=salary+salary*0.12
      print("After increment salary is: ",salary)
    elif rating=='C':
      print("Increment is 10%")
      salary=salary+salary*0.10
      print("After increment salary is: ",salary)
    else:
      print("Increment is 6%")
      salary =salary+salary *0.06
      print("After increment salary is: ",salary)

  elif salary < 1000000:
   rating=input("Enter increment ratings:(A/B/C/D)").upper()
   if rating=='A':
    print("Increment is 14%")
    salary=salary+salary*0.14
    print("After increment salary is: ",salary)
   elif rating=='B':
    print("Increment is 10%")
    salary=salary+salary*0.10
    print("After increment salary is: ",salary)
   elif rating=='C':
    print("Increment is 8%")
    salary=salary+salary*0.8
    print("After increment salary is: ",salary)
   else:
    print("Increment is 6%")
    salary =salary+salary *0.06
    print("After increment salary is: ",salary)

  elif salary < 1500000:
   rating=input("Enter increment ratings:(A/B/C/D)").upper()
   if rating=='A':
    print("Increment is 8%")
    salary=salary+salary*0.8
    print("After increment salary is: ",salary)
   elif rating=='B':
    print("Increment is 6%")
    salary=salary+salary*0.6
    print("After increment salary is: ",salary)
   elif rating=='C':
    print("Increment is 4%")
    salary=salary+salary*0.4
    print("After increment salary is: ",salary)
   else:
    print(" NO Increment so salary is same  ",salary)

  elif salary < 2300000:
   rating=input("Enter increment ratings:(A/B/C/D)").upper()
   if rating=='A':
    print("Increment is 7%")
    salary=salary+salary*0.7
    print("After increment salary is: ",salary)
   elif rating=='B':
    print("Increment is 5%")
    salary=salary+salary*0.5
    print("After increment salary is: ",salary)
   elif rating=='C':
    print("Increment is 4%")
    salary=salary+salary*0.4
    print("After increment salary is: ",salary)
   else:
    print(" NO Increment so salary is same ",salary)

info(salary)

info(salary)

"""13.	Ask user to opt for courses for master degree based on the following
L1 = [“HR”, “Finance”, “Marketing”, “DS”]

Based on above subject there are two different streams. For example- HR is having HR core and HR analytics and Marketing is having core and Marketing analytics.
Analytics is the optional subject and having added extra fees.

DS is not having analytics.

If fees for L1 is 2 lakhs for each course core subject having the same fees but analytics subject having 10% extra on 2 lakhs.

If student opts for hostel then 2 lakhs per year is added. For food monthly 2000 .

Transportation charges 13000 per semester. Calculate the total annual cost based on selected service.

User will enter values as subject, analytics(Y/N), Hostel (Y/N), food(How many months?), Transportation(semester/annual)

"""

L1=["HR","Finance","Marketing","DS"]
fees=200000
total=0

subject=input("Enter a subject:")
analytics=input("Is it analytics related(Yes/No) : ")
hostel=input("Are u living in hostel(yes/No): ")
food=int(input("Food: how many months? :"))
transport=input("Transportation(semester/annual) :")

if subject in L1:
    total=total+fees
    if analytics=="Yes":
      if subject != "DS":    #Analytics subject fees except DS
        total=total+fees*0.10
      else:
        print("Analytics not available for DS.")

    if hostel=="Yes":  #Hostel fees
      total=total+200000

    total=total+2000*food  #Food fees

    if transport == "semester":    #transportation
      total=total+13000
    elif transport == "annual":
      total=total+13000 * 2

    print("Total Annual Cost=",total)

else:
  print("Invalid Subject")

"""
14.	Digitalize the book allotment process for school. Charges are mentioned here in the given table:
"""

#Simple
Books={"Hindi":{'1-4':60,'5-8':100,'9-10':150},
       "Marathi":{'1-4':60,'5-8':100,'9-10':150},
       "English":{'1-4':80,'5-8':100,'9-10':150},
       "Science":{'1-4':90,'5-8':120,'9-10':200},
       "Maths":{'1-4':100,'5-8':140,'9-10':250}}

Notebooks={"square":{100:40,200:70},
           "4lines":{100:30,200:50},
           "2lines":{100:30,200:50},
           "single lines":{100:60,200:100},
           "A4":{100:100,200:180}}

total=0
buy=input("Do you want to buy Books (Y/N) :").upper()


if buy=='Y':
 Standard=input("Enter class(1-4/5-8/9-10): ")
 subject=input("Enter subject name(Hindi/Marathi/English/Science/Maths): ").capitalize()

 price=Books[subject][Standard]
 total+=price
elif buy=='N':
  print("You can buy Notebook ! Thank you !!!")

N_buy=input("Do u want buy notesbooks(Y/N) :").upper()
if N_buy=='Y':
 note_type=input("Enter type of notebook: ")
 pages=int(input("Enter pages (100/200) :" ))

 noteprice=Notebooks[note_type][pages]
 total+=noteprice
elif N_buy=='N':
  print("Thank You !!!")

print("\nTotal amount:",total)

Books = {
    "Hindi": {'1-4':60,'5-8':100,'9-10':150},
    "Marathi": {'1-4':60,'5-8':100,'9-10':150},
    "English": {'1-4':80,'5-8':100,'9-10':150},
    "Science": {'1-4':90,'5-8':120,'9-10':200},
    "Maths": {'1-4':100,'5-8':140,'9-10':250}
}

Notebooks = {
    "square":{100:40,200:70},
    "4lines":{100:30,200:50},
    "2lines":{100:30,200:50},
    "single lines":{100:60,200:100},
    "a4":{100:100,200:180}
}

receipt = {}
total_cost = 0

print("\n===== Welcome to Book Store =====")

while True:

    choice = input("\nWhat do you want to buy? (Book/Notebook): ").lower()

    # ---------------- BOOK ----------------
    if choice == "book":
        standard = input("Enter class (1-4/5-8/9-10): ")
        subject = input("Enter subject: ").capitalize()
        qty = int(input("Enter quantity: "))

        if subject in Books and standard in Books[subject]:

            unit_price = Books[subject][standard]
            item_total = unit_price * qty
            item_key = subject + " Book"

            total_cost += item_total

            receipt[item_key] = {
                "standard": standard,
                "qty": qty,
                "unit_price": unit_price,
                "total": item_total
            }

        else:
            print("Invalid Book Details!")

    # ---------------- NOTEBOOK ----------------
    elif choice == "notebook":
        note_type = input("Enter notebook type: ").lower()
        pages = int(input("Enter pages (100/200): "))
        qty = int(input("Enter quantity: "))

        if note_type in Notebooks and pages in Notebooks[note_type]:

            unit_price = Notebooks[note_type][pages]
            item_total = unit_price * qty
            item_key = note_type.capitalize() + " Notebook"

            total_cost += item_total

            receipt[item_key] = {
                "pages": pages,
                "qty": qty,
                "unit_price": unit_price,
                "total": item_total
            }

        else:
            print("Invalid Notebook Details!")

    else:
        print("Invalid Choice!")

    more = input("\nDo you want anything more? (Y/N): ").upper()
    if more != 'Y':
        break


# ----------- SHOW STORED DICTIONARY -----------
print("\nStored Receipt Dictionary:\n")
print(receipt)


# ---------------- PRINT RECEIPT ----------------
print("-"*85)
print("|{:^83}|".format("WELCOME TO BOOK STORE"))
print("|{:^83}|".format("RECEIPT"))
print("-"*85)

print("|{:^4}|{:^25}|{:^12}|{:^8}|{:^15}|".format(
    "Sr","Item","Std/Page","Qty","Total"))
print("-"*85)

for index, (item, details) in enumerate(receipt.items(), start=1):

    if "standard" in details:
        extra = details["standard"]
    else:
        extra = str(details["pages"])

    print("|{:^4}|{:^25}|{:^12}|{:^8}|{:^15.2f}|".format(
        index,
        item,
        extra,
        details["qty"],
        details["total"]
    ))

print("-"*85)
print("|{:>65} {:>15.2f} |".format("Grand Total", total_cost))
print("-"*85)

print("\nThank You for Shopping! ")

receipt

"""#Using the function
1.take input from user that ask which books you want to buy or which notebooks he wants make dictionary of that order

2. calculate overall bill

3.print bill
"""

def buy_book(Books, receipt, total_cost):

    standard = input("Enter class (1-4/5-8/9-10): ")
    subject = input("Enter subject: ").capitalize()
    qty = int(input("Enter quantity: "))

    if subject in Books and standard in Books[subject]:

        unit_price = Books[subject][standard]
        item_total = unit_price * qty
        item_key = subject + " Book"

        total_cost = total_cost + item_total

        receipt[item_key] = {
            "standard": standard,
            "qty": qty,
            "total": item_total
        }

    else:
        print("Invalid Book Details!")

    return total_cost


def buy_notebook(Notebooks, receipt, total_cost):

    note_type = input("Enter notebook type: ").lower()
    pages = int(input("Enter pages (100/200): "))
    qty = int(input("Enter quantity: "))

    if note_type in Notebooks and pages in Notebooks[note_type]:

        unit_price = Notebooks[note_type][pages]
        item_total = unit_price * qty
        item_key = note_type.capitalize() + " Notebook"

        total_cost = total_cost + item_total

        receipt[item_key] = {
            "pages": pages,
            "qty": qty,
            "total": item_total
        }

    else:
        print("Invalid Notebook Details!")

    return total_cost


def print_receipt(receipt, total_cost):

    print("\n---------- RECEIPT ----------")

    for item, details in receipt.items():

        if "standard" in details:
            extra = details["standard"]
        else:
            extra = details["pages"]

        print("Item:", item,
              "| Std/Page:", extra,
              "| Qty:", details["qty"],
              "| Total:", details["total"])

    print("-----------------------------")
    print("Grand Total:", total_cost)
    print("-----------------------------")


Books = {
    "Hindi": {'1-4':60,'5-8':100,'9-10':150},
    "Marathi": {'1-4':60,'5-8':100,'9-10':150},
    "English": {'1-4':80,'5-8':100,'9-10':150},
    "Science": {'1-4':90,'5-8':120,'9-10':200},
    "Maths": {'1-4':100,'5-8':140,'9-10':250}
}

Notebooks = {
    "square":{100:40,200:70},
    "4lines":{100:30,200:50},
    "2lines":{100:30,200:50},
    "single lines":{100:60,200:100},
    "a4":{100:100,200:180}
}

receipt = {}
total_cost = 0

print("\nWelcome to Book Store")

while True:

    choice = input("\nBook or Notebook: ").lower()

    if choice == "book":
        total_cost = buy_book(Books, receipt, total_cost)

    elif choice == "notebook":
        total_cost = buy_notebook(Notebooks, receipt, total_cost)

    else:
        print("Invalid Choice")

    more = input("Anything more? (Y/N): ").upper()
    if more != "Y":
        break

print_receipt(receipt, total_cost)

"""15.	Create an interest bucket for Fix Deposit in the bank. Ask user to enter start date and end date for the FD and check which bucket list it belongs to and assign the interest rate"""

#simple way
import sys
from datetime import datetime
try:
    start = input("Enter start date (YYYY-MM-DD): ")
    end = input("Enter end date (YYYY-MM-DD): ")

    d1 = datetime.strptime(start, "%Y-%m-%d").date() #converting str to date
    d2 = datetime.strptime(end, "%Y-%m-%d").date()

    days = (d2 - d1).days

    print("Total days:", days)

    if days < 7:
        print("FD should be minimum 7 days")

    else:
        person = input("Enter type (public/senior): ").lower()

        if 7 <= days <= 45:
            if person == "public":
                print("Interest rate is 5.75%")
            elif person == "senior":
                print("Interest rate is 6.25%")

        elif 46 <= days <= 179:
            if person == "public":
                print("Interest rate is 6.25%")
            elif person == "senior":
                print("Interest rate is 6.75%")

        elif 180 <= days <= 210:
            if person == "public":
                print("Interest rate is 6.35%")
            elif person == "senior":
                print("Interest rate is 6.85%")

        elif 211 <= days < 365:
            if person == "public":
                print("Interest rate is 6.40%")
            elif person == "senior":
                print("Interest rate is 6.90%")

        elif 365 <= days < 730:
            if person == "public":
                print("Interest rate is 7.00%")
            elif person == "senior":
                print("Interest rate is 7.50%")

        elif 730 <= days < 1095:
            if person == "public":
                print("Interest rate is 6.75%")
            elif person == "senior":
                print("Interest rate is 7.25%")

        elif 1095 <= days < 1825:
            if person == "public":
                print("Interest rate is 6.70%")
            elif person == "senior":
                print("Interest rate is 7.20%")

        elif 1825 <= days <= 3650:
            if person == "public":
                print("Interest rate is 6.60%")
            elif person == "senior":
                print("Interest rate is 7.10%")

        else:
            print("Duration not available")

except:
  print(sys.exc_info())

#using dictionary
from datetime import datetime

# Take input
start = input("Enter start date (YYYY-MM-DD): ")
end = input("Enter end date (YYYY-MM-DD): ")

d1 = datetime.strptime(start, "%Y-%m-%d").date()
d2 = datetime.strptime(end, "%Y-%m-%d").date()

days = (d2 - d1).days

if days < 7:
    print("FD must be minimum 7 days")
else:
    customer = input("Enter customer type (public/senior): ").lower()
    rate_type = input("Enter rate type (existing/revised): ").lower()

    # Interest bucket data
    buckets = [
        (7, 45, 5.75, 5.75, 6.25, 6.25),
        (46, 179, 6.25, 6.25, 6.75, 6.75),
        (180, 210, 6.35, 6.35, 6.85, 6.85),
        (211, 364, 6.40, 6.40, 6.90, 6.90),
        (365, 729, 6.80, 7.00, 7.30, 7.50),
        (730, 1094, 6.80, 6.75, 7.30, 7.25),
        (1095, 1824, 6.80, 6.70, 7.30, 7.20),
        (1825, 3650, 6.85, 6.60, 7.35, 7.10)
    ]

    for bucket in buckets:
        min_d, max_d, pub_old, pub_new, sen_old, sen_new = bucket

        if min_d <= days <= max_d:

            if customer == "public":
                rate = pub_old if rate_type == "existing" else pub_new
            elif customer == "senior":
                rate = sen_old if rate_type == "existing" else sen_new
            else:
                print("Invalid customer type")
                break

            print("Interest Rate:", rate)
            break
    else:
        print("Duration not supported")

#16.
string = """In most organized forms of writing, such as essays, paragraphs contain a topic sentence.
This topic sentence of the paragraph tells the reader what the paragraph will be about.
Essays usually have multiple paragraphs that make claims to support a thesis statement, which is the central idea of the essay.    """

"""Type casting (Observe the errors and note it down for all conversions.)

17. int can convert to:

**int → str**

**int → float**
"""

#17.
a=100

b=str(a)
type(b)
b

#'int' object is not iterable so list,tuple,dict,set
l=list(a)
type(l)

t=tuple(a)
type(t)

d=dict(a)
type(d)

s=set(a)
type(s)

b=float(a)
type(b)
b

#18.
city="Pune"

"""String can convert to:

list

tuple

set
"""

#int and float :ValueError: invalid literal for int() with base 10: 'Pune'
#could not convert string to float: 'city'
type(int(city))

type(float(city))

type(list(city))
print(list(city))

caa="pune"
tup = tuple(caa)
print(tup)

a=dict(city) #ValueError: dictionary update sequence element #0 has length 1; 2 is required
type(a)

c="pune"
s=set(c)
type(s)

#18.
marks=[20,18,15,17,18]

"""List can convert to:

tuple

set

list (copy)
"""

i=int(marks)
print(type(i))

i=float(marks)
print(type(i))

i=list(marks)
print(list(i))

marks=[20,18,15,17,18]
i=tuple(marks)
print(type(i))

marks=[20,18,15,17,18]
d=dict({marks})
type(d)

marks=[20,18,15,17,18]
i=set(marks)
print(type(i))

"""**List Operations:**"""

#10.
snames=[]
#type(snames)

print(snames.append(20))
snames

print(snames.extend([30]))

snames

print(snames.append(50))

print(snames.extend(["work"]))

combo=[1, 'a’', 'b' ,2 , 3]

print(combo+snames)

snames.append(combo)

snames

snames.extend(combo)

#11.
l1=[1,2]
l3=[1,2,3,4,5,6,7]
l1.insert(3,5)
l1

#12.
list1=[1,2,3,['a', 'b', 'c'], 100, 'Nisha', 20.50, 90.10 ]
result=[]
for i in list1:
  if isinstance(i,(int,float)):
    result.append(i)
  else:
    result.append(i)
print(result)

list1.remove('Nisha')
list1

p=list1.index(20.5)
p

#13
list(i**2 for i in range(1,11))

#14
list(n for n in range(1,200+1) if n%13==0 )

#15
list(item for item in range(300,401) if item%4==0)

#16
x=2
y=2

result=[[i,j] for i in range(x) for j in range(y)]

print(result)

"""17. add() adds single element, update() adds multiple elements.

18. append() adds whole item, extend() adds elements individually.

19. pop() removes by index and returns value, remove() removes by value.

20.remove() gives error if value not found, discard() does not give error, pop() removes random element.
"""

#17.
s = {1,2}
s.add(3)

s.update([4,5])
print(s)

#18.
l = [1,2]
l.append([3,4])
l

l.extend([3,4])
l

#19.
l.remove(4)
l

l.pop(1)

#20.
s.remove(20) #remove() gives error if value not found,

s.discard(20)

#21.
x=set()
type(x)

#22.
s1={1,2,3,4,'a','s'}
s2={4,'s',5,6,7,8}

print(s1|s2) #union
print(s1 & s2) #intersection
print(s1-s2) #differnce
print(s1^s2)  #symmetric difference

#23.
s1={1,2,3,4,'a','s'}
l2=[12,14,15,16,17,18]
print(s1|l2) #union
print(s1 & l2) #intersection
print(s1-l2) #differnce
print(s1^l2)  #symmetric difference

#Set operations work only between sets, not list.

#24.
name=input("Enter a name:").upper()
DOB=input("Enter DOB as DD-MM-YYYY:")
password=name[:4]+'@'+DOB[:2]+DOB[3:5]
print(password)

#25.
name=input("Enter a name:").upper()
DOB=input("Enter DOB as DD-MM-YYYY:")
password=name[:4]+'@'+DOB[6:]
print(password)

#26.
n=4
for i in range(n):
  for j in range(i+1):
    print("*",end=" ")
  print()

#27.
n=4
for i in range(n):
  for j in range(n-i):
    print("*",end=" ")
  print()

#28.
str_val="ABCD"
for i in range(len(str_val)):
   for j in range(i+1):
     print(str_val[j],end=' ')
   print()

#29.
str_val="ABCD"
for i in range(len(str_val)):
   for j in range(i+1):
     print(str_val[i],end='')
   print()

#30.
n=4
for i in range(1,n+1):
   for j in range(i):
     print(i,end='')
   print()

#31.
val="ABCD"
rev=val[::-1]
for i in range(len(val)):
  for j in range(i+1):
    print(rev[j],end="")
  print()

#32.
string=input("Enter a string:").upper()
rev=string[::-1]
for i in range(len(string)):
  for j in range(i+1):
    print(rev[j],end="")
  print()

#33.
#using a loop
list1=[]
for i in range(1,11):
  if i%2!=0:
    list1.append(i)
print(list1)

#using comprehensive list
l1=[i for i in range(1,11) if i%2!=0]
print(l1)

#34.
list1=[]
for i in range(200,251):
  if i%2==0:
    list1.append(i)
print(list1)

#35.
List2 = [2,70,'work','para', 2.5, [1,2,3], (1,2), {1,2}, {1:'a', 2:'b'}, 3,10,302.5]
print(List2*2)
#Multipling it create twice of elements in list means copy of list but eaxh element in list twise

#36.
list2 = [2,70,'work', 'para', 2.5, [1,2,3], (1,2), {1,2}, {1:'a', 2:'b'}, 3,10,302.5]
list3=[]
for i in list2:
  if isinstance(i,(int,float,str,list,tuple)):
    list3.append(i*2)
  else:
    list3.append(i)
print(list3)

#37.Create a function to accept marks from user utilize exception concept to validate proper marks.
def grade( ):
 while True:
    try:
      marks=float(input("Enter a marks: "))

      if marks < 0 or marks >100:
        raise Exception
      print("Succefully Done.")
      return marks
    except ValueError:
      print("Enter valid marks.")
    except Exception:
      print("Enter proper marks.")

grade()

"""38.	Create a function to validate user first name/last name. User first name/last name should contain only characters. No special characters, numbers, space in name"""

f_name=input("Enetr a first name: ").capitalize()
l_name=input("Enter a last name: ").capitalize()
def name(f_name,l_name):
  if f_name.isalpha() and l_name.isalpha():
    return f_name,l_name
  else :
    return "Enter a correct names."
name(f_name,l_name)

#using try / exception
def info():
  while True:
    try:
        f_name=input("Enetr a first name: ").capitalize()
        l_name=input("Enter a last name: ").capitalize()
        if not f_name.isalpha() and not l_name.isalpha():
            raise Exception
        else :
            return f_name,l_name
    except Exception:
       print("Enter valid names.")

info()

"""39.Create a function to accept mobile number. Mobile number should contain 10 digits. No Special character, alphabets and space."""

mb=input("Enter a mobile number:")
def number(mb):
  if mb.isdecimal() and len(mb)==10:
    return int(mb)
  else:
    return "Enter a correct mb number."

number(mb)

#using Exceptions
def number():
  while True:
    try:
      mb=input("Enter a mobile number:")
      if mb.isdecimal() and len(mb)==10:
        print("Call me later.")
        return int(mb)
      else:
        raise Exception
    except Exception:
      print("Enter valid mb number.")

    #finally:
     # print("Call me later.")

number()

##another method mam given
def val_mobile(mb):
  if mb.isdigit() and len(mb)==10:
    val=mb
    flag=True
  else:
    val="Error"
    flag=False
  return val,flag

def accept_input():
  name=input("Enter the name:")
  mobile=input("Enter mobile:")

  return name,mobile

input_val=accept_input()

val_mobile('7887438088')

"""40.	Create a function to generate auto-password based on specific person details. Ask user to enter name, DOB. And password must be First name 4 characters and year of birth."""

name=input("Enter a name:").upper()
DOB=input("Enter DOB(DD-MM-YYYY): ")

def generate_pass(name,DOB):
  if len(name)<4 or len(DOB)<10 or not name.isalpha():
    return "Enter a details in correct format."
  else:
    password=name[:4]+DOB[6:]
    return password

generate_pass(name,DOB)

"""41.	Create a empty dictionary and ask user to enter values as name, DOB, mobile number add all the details in dictionary with customer number as 1 for first time. If user try to enter another value, then number should increase as 2 with new details and previous values should not change.

For example:
{}
{1:{name : "Sachin", "DOB": "21-06-1965" , "mobile": "1234123423"}}

{1:{name : "Sachine", "DOB": "21-06-1965" , "mobile": "1234123423"},
2: {name : "Sumedh", "DOB": "02-02-2002" , "mobile": "1234123433"}}

"""

detail={}
def info_dict():
  while True:
    seq=len(detail)+1
    name=input("Enter a name:").capitalize()
    DOB=input("Enter DOB(DD-MM-YYYY)")
    mb=int(input("Enter a mb :"))

    detail[seq]={"name":name,"DOB":DOB,"mb":mb}

    choice=input("Do you want enter more details(Y/N) :").upper()
    if choice=='N':
      break

  return detail

info_dict()

detail

"""42.	Based on the above example create the dictionary and save the same in a cust_info.txt or cust_info.log"""

#file handling
f=open("cust_info","w")
f.write(str(detail))
f.close()

"""43.	Based on the above example read the file cust_info.txt . check if dictionary any information is available in the file. If there is information then read the dictionary store into one variable and then append new information of customer if added.

"""

try:
    f = open("cust_info", "r")
    content = f.read()
    f.close()

    if content == "":
        detail = {}
    else:
        detail = eval(content)

except FileNotFoundError:
    detail = {}

seq = len(detail) + 1
name = input("Enter name: ")
dob = input("Enter DOB: ")
mb = input("Enter mobile: ")

detail[seq] = {"name": name, "DOB": dob, "mb": mb}

f = open("cust_info", "w")
f.write(str(detail))
f.close()

print("Data saved successfully!")

"""44.	Create a table  cust_info as sr_no, name, DOB, mobile. Ask user to enter the information from python code. Validate all fields and after validation insert records in the table."""

import sqlite3
from datetime import datetime

conn = sqlite3.connect("customer.db")  # Connect to database
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS cust_info (
    sr_no INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    DOB TEXT NOT NULL,
    mobile TEXT NOT NULL
)
""")                              # Creating table

# Name validation
while True:
    name = input("Enter name: ")
    if name.isalpha():
        break
    else:
        print("Invalid name. Only letters allowed.")

# DOB validation
while True:
    dob = input("Enter DOB (YYYY-MM-DD): ")
    try:
        datetime.strptime(dob, "%Y-%m-%d")
        break
    except:
        print("Invalid date format.")

# Mobile validation
while True:
    mobile = input("Enter mobile (10 digits): ")
    if mobile.isdigit() and len(mobile) == 10:
        break
    else:
        print("Invalid mobile number.")

cursor.execute(
    "INSERT INTO cust_info (name, DOB, mobile) VALUES (?, ?, ?)",
    (name, dob, mobile)
)

conn.commit()
conn.close()

print("Record inserted successfully!")

#45.sort the dict by values
dict1= {'Key': {'subkey':20} ,  'k2':{'sub2' : 5}, 'k3' : {'sub4' :16},  'k4': {'sub4': 6}}

result_values=sorted(dict1.items(),key=lambda i: list(i[1].values())[0])
dict(result_values)

#46.
from datetime import date, datetime
def calculate_age(dob_string):
    today = date.today()
    dob = datetime.strptime(dob_string, "%Y-%m-%d").date()

    age = today.year - dob.year

    if (today.month, today.day) < (dob.month, dob.day): # To Check if birthday has not come yet this year
        age -= 1

    return age

dob = "2002-02-14"
print("Age is:", calculate_age(dob))

"""47.	Create a function to check age eligibility for given customer based on DOB. Function will take two input DOB and ELIGIBILITY age."""

from datetime import date, datetime
def check_eligibility(dob_string, eligibility):
    today = date.today()
    dob = datetime.strptime(dob_string, "%Y-%m-%d").date()

    age = today.year - dob.year

    if (today.month, today.day) < (dob.month, dob.day):
        age -= 1
    print("Age is:", age)

    if age >= eligibility:
        print("You are eligible")
        return True
    else:
        print("You are not eligible")
        return False

eligibility = 18
dob = "2002-02-14"

check_eligibility(dob, eligibility)

"""48.	Create a function to check if string is palindrome or not ? For example, if input is NITIN then reverse of the string is same then it is palindrome. If input is ANIL then reverse is LINA which is not same then it is not palindrome.  """

def pali():
  string=input("Enter a string:")
  if string.lower()==string[::-1].lower():
    return "String is palindrome."
  else:
    return "String is not Palindrome."
pali()

#Using Exception:
import sys
def palindrome():
  while True:
    try:
      string=input("Enter a string:")
      if string.upper()==string[::-1].upper():
        print("String is palindrome.")
        return string
      else:
        raise Exception

    except Exception:
      print("String is not Palindrome.")
    except:
      print(sys.exc_info()[1])
palindrome()

"""49.	Create a function to generate a Fibonacci Series. 0 1 1 2 3 5 8 13 21 34 …..  upto 100"""

def fib(n):
  a=0
  b=1
  while a<n:
    print(a)
    a,b=b,a+b
fib(100)

"""50.	Write a code to generate factorial of the number  For example: factorial of 5 = 5! = 5*4*3*2*1"""

n=5
fact=1
for i in range(1,n+1):
  fact*=i

print(fact)

#51.	Write a program to find largest number in the list.
list1=[10,20,30,50,60,100,90]
large=list1[i]
for i in list1:
  if i > large:
    large=i
print(large)

#52.	Write a program to check frequency of each element in the list.
l1=[1,2,5,6,4,3,6,1,2]
frq={}
for i in l1:
  if i in frq:
    frq[i]+=1
  else:
    frq[i]=1

frq

#53.	There are two string l1 =[ 1,2,3,4,5] and l2 =[3,2,8,7,9] then write a program to find common elements in the list.
l1 =[ 1,2,3,4,5]
l2 =[3,2,8,7,9]

result=list(set(l1) & set(l2))
print(result)

l1 =[ 1,2,3,4,5]
l2 =[3,2,8,7,9]
l=[]
for i in l1:
  if i in l2:
    l.append(i)
l

"""54.	Create 3 tables  in mysql having the columns as mentioned
1) user : uid, mobile, passkey, date
2) Product : pid, pname
3) Order : oid, uid, pid

user having  attribute uid, mobile
	      method user sign up
			sign in
			view_products
			view_orders
			place_order
Based on the OOPs concept create classes, methods, attributes and insert information

"""

class Product:

    products = []

    def __init__(self, pid, pname):
        self.pid = pid
        self.pname = pname
        Product.products.append(self)


class Order:

    orders = []

    def __init__(self, oid, uid, pid):
        self.oid = oid
        self.uid = uid
        self.pid = pid
        Order.orders.append(self)


class User:

    users = []

    def __init__(self, uid, mobile, passkey, date):
        self.uid = uid
        self.mobile = mobile
        self.passkey = passkey
        self.date = date
        User.users.append(self)

    def sign_in(self, mobile, passkey):
        if self.mobile == mobile and self.passkey == passkey:
            print("Login successful")
            return True
        else:
            print("Invalid credentials")
            return False

    def view_products(self):
        print("Available Products:")
        for product in Product.products:
            print(product.pid, product.pname)

    def place_order(self, pid):
        oid = len(Order.orders) + 1
        Order(oid, self.uid, pid)
        print("Order placed successfully")

    def view_orders(self):
        print("Your Orders:")
        for order in Order.orders:
            if order.uid == self.uid:
                print("Order ID:", order.oid, "Product ID:", order.pid)

Product(1, "Laptop")
Product(2, "Mobile")
Product(3, "Headphones")

u1 = User(1, "9876543210", "1234", "2026-02-15")

if u1.sign_in("9876543210", "1234"):
    u1.view_products()
    u1.place_order(1)
    u1.view_orders()

"""56.Build a function to print bill. Generate the bill as mentioned below."""

a=int(input("Enter a series Numbers:"))
b=input("Enter food name: ")
c=int(input("Enter Quantity: "))
d=int(input("Price of food:"))

print("Plz Pay Bill")
print("-"*50)
print("|{:>35}".format("Welcome to Hotel NIL-SAGAR"))
print("-"*50)

print("|sr","        Menu","           Qunt","         price  |")

print("|{0:<10} {1:<15} {2:<10} {3:>8}  |".format(a,b,c,d))

print("-"*50)
t="Total"
print("|{0:<8} {1:>37}  |".format(t,c*d))
print("-"*50)

